### ISSUE TITLE
"Undefined offset: 0" in SQLQuery.php when opening a product

### ISSUE THREAD

**Issue by icecaster** [swipestripe/silverstripe-swipestripe#1]
When creating a new product / querying for them 

Notice: "Undefined offset: 0" at line 382 of /var/www/chillstore/httpdocs/sapphire/core/model/SQLQuery.php

this happens using SS 2.4.6 and the latest HEAD of swipestripe.

will try to fix and update here

**Comment by icecaster** [comment]
In product.php on the lines
463 & 464 you are unsetting $query->select[0] & $query->select[1]

This is required to be set in SQLQuery
On line 382: $select = is_array($this->select) ? $this->select[0] : $this->select;

Hence this is throwing a notice when key 0 is not set.

Am unsure what you are trying to achieve with this modification.
Have commented the two unsetters, restored working

**Comment by frankmullenger** [comment]
Ahh, ok. Interesting, I added that because of the Money composite db field. That money field is the bane of my existence haha. Basically in Money::addToQuery() it does this:
$query->select[] = sprintf('"%sAmount"', $this->name);
$query->select[] = sprintf('"%sCurrency"', $this->name);

Which creates bugs in SQL queries involving more than one DO with the Money fields of the same name. This really needs to add the DO like:
$query->select[] = sprintf('"DOName"."%sAmount"', $this->name);

My fix was a bit of a dirty hack which clearly doesn't work for products in the site tree, I'll report this on trac and see if I can fix properly.

Cheers mate!

**Comment by frankmullenger** [comment]
So, if you try to load a category page with the unsetters commented out you'll probably get SQL error like: Duplicate column name 'AmountAmount'.

I assumed this was because there were 2 DOs in the queries with 'Amount' money fields, but looking closer there is only one DO in the query and what seems to be happening is Money->addToQuery() is being called and injecting a couple of fields into the select array at indices 0 and 1.

This is done before these lines in DO:

$query->select[] = "\"$baseClass\".\"ID\"";
$query->select[] = "CASE WHEN \"$baseClass\".\"ClassName\" IS NOT NULL THEN \"$baseClass\".\"ClassName\" ELSE '$baseClass' END AS \"RecordClassName\"";

Then SQLQuery->sql() expects $baseClass.ID at index 0 but instead AmountAmount is there and throws the error.

e.g: WRONG
(
    [0] => "AmountAmount"
    [1] => "AmountCurrency"
    [2] => "SiteTree"."ID"
    [3] => CASE WHEN "SiteTree"."ClassName" IS NOT NULL THEN "SiteTree"."ClassName" ELSE 'SiteTree' END AS "RecordClassName"
)

RIGHT
(
    [0] => "Member"."ID"
    [1] => CASE WHEN "Member"."ClassName" IS NOT NULL THEN "Member"."ClassName" ELSE 'Member' END AS "RecordClassName"
)

I will patch it up best I can for SwipeStripe and log a ticket for Ingo.

Patched:
https://github.com/frankmullenger/silverstripe-swipestripe/commit/9d08b1aefadb092807439e991660813d8a044d86

Ticket raised:
http://open.silverstripe.org/ticket/6848

**Comment by icecaster** [comment]
Great, thanks!
