### ISSUE TITLE
Too generic CSS Selectors

### ISSUE THREAD

**Issue by icecaster** [swipestripe/silverstripe-swipestripe#3]
This is a rather annoying issue.

On CartForm.ss
CartQuantityField.ss and many more

you are using classes "left" and "right" to align text within table cells.

Some css frameworks (foundation in this case) use these classes to float elements, causing these elements to float all over the place.

Causing me having to overwrite almost every template file, just for the sake of renaming classes.

Suggestion:

rewrite all templates and css.
Only use prefixed classes as selectors:
sws_align-right

Still use ids on common elements in the markup, however do not use them in the css.

**Comment by frankmullenger** [comment]
Cheers mate, I'll have to look into this I like your suggestions. 

Instead of prefixing each class selector with swipestripe- or similar could I just wrap these templates in a div.swipestripe ?

I'll still move away from the generic left and right selectors. I didn't put much thought/effort into the html templates tbh, agree they need some work.

**Comment by frankmullenger** [comment]
Fixed: https://github.com/frankmullenger/silverstripe-swipestripe/commit/25e51a12587afb6f466a2889e95e59108c3559e9
