### ISSUE TITLE
Emogrifier throwing deprecation error

### ISSUE THREAD

**Issue by stevie-mayhew** [swipestripe/silverstripe-swipestripe#69]
![emogrifier](https://cloud.githubusercontent.com/assets/1953220/3590910/1e3f636c-0c5e-11e4-93f0-305e44ef9c4d.png)

**Comment by Zauberfisch** [comment]
updating emogrifier should do the trick.

they already fixed this issue: https://github.com/jjriv/emogrifier/pull/26
since emogrifier also uses composer, how about we add it as a dependency instead of having the file on our repo? 
@frankmullenger any specific reason why emogrifier is not included via composer, or was that just before the composer time?

**Comment by frankmullenger** [comment]
@Zauberfisch you're right, it was before composer. Great idea to move this to composer!

**Comment by bummzack** [comment]
Created a PR for this #90

**Comment by stevie-mayhew** [comment]
Thanks @bummzack
