### ISSUE TITLE
The reference between product, item, cart and order

### ISSUE THREAD

**Issue by luukgruijs** [swipestripe/silverstripe-swipestripe#75]
Hi all,

I'm extending this awesome module so my client can add taxes to products. I can't use the tax module since that supports only one tax rate per country. In Holland we have different taxrates for different product groups. 

Please tell me if the code could be better written or something like that.
I've extend the product class like this:

class Product_Extend extends DataExtension {
    private static $db = array(
        "Taxrate" => "INT(21)",
        "BTW" => "Decimal(19,8)"
    );

```
public function updateCMSFields(FieldList $fields) {
    $fields->addFieldToTab("Root.Main", new DropDownField("Taxrate", "BTW", array('21' => "21%",'6' => "6%")));
    return $fields;
}

public function calculateBTW() {
    $btw = $this->owner->BTW;
    $productPrice = $this->owner->Price;
    $tax = $this->owner->Taxrate;
    $btw = $productPrice * ($tax / 100);
    DB::query('UPDATE Product SET BTW = '. $btw . ' WHERE ID = '. $this->owner->ID . '');
}
```

}

This gives the user the option to chose a taxrate per product. The default is 21%. After that it calculates the tax and stores it in the database. This all works fine...

however i'm kinda stuck right now. correct me if i'm wrong, but the item class inherits the product values for usage in the cart. How can i pass those BTW and taxrate values to the item table? After that it shouldn't be much of a hassle to get them in the final order.

Thanks in advance

**Comment by silverstripe-elliot** [comment]
Overload the function "augmentDatabase" in your Product_Extend. In this function you should call DB::alterTable() to update your database tables when running dev/build. There's an explanation under "Custom database generation" here: http://doc.silverstripe.org/framework/en/reference/dataextension. You might also have a look around in the unit tests for the framework to see how augmentDatabase() is used on other extensions.

Why are you using DB::query() here, instead of $this->owner->BTW?

**Comment by frankmullenger** [comment]
@luukgruijs Elliot's idea to use augmentDatabase() is a good one. You can also copy the swipestripe-flatfeetax module and alter it so that it calculates tax based on the fields you have added to product. 

So you don't want the Item to have the tax element attached, but you want to create a new Modification for the order, the Modification is calculated during the order process so you can add your logic for generating the tax component there.
